-- Insert dummy data for department table
insert into department (name) values ('Human Resources');
insert into department (name) values ('Marketing');
insert into department (name) values ('Accounting');
insert into department (name) values ('Engineering');
insert into department (name) values ('Business Development');
insert into department (name) values ('Business Development');
insert into department (name) values ('Services');
insert into department (name) values ('Business Development');
insert into department (name) values ('Services');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Training');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Services');
insert into department (name) values ('Business Development');
insert into department (name) values ('Training');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Sales');
insert into department (name) values ('Business Development');
insert into department (name) values ('Marketing');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Support');
insert into department (name) values ('Product Management');
insert into department (name) values ('Engineering');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Services');
insert into department (name) values ('Engineering');
insert into department (name) values ('Support');
insert into department (name) values ('Business Development');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Services');
insert into department (name) values ('Training');
insert into department (name) values ('Product Management');
insert into department (name) values ('Business Development');
insert into department (name) values ('Engineering');
insert into department (name) values ('Engineering');
insert into department (name) values ('Training');
insert into department (name) values ('Business Development');
insert into department (name) values ('Accounting');
insert into department (name) values ('Services');
insert into department (name) values ('Support');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Support');
insert into department (name) values ('Training');
insert into department (name) values ('Marketing');
insert into department (name) values ('Legal');
insert into department (name) values ('Services');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Support');
insert into department (name) values ('Product Management');
insert into department (name) values ('Engineering');
insert into department (name) values ('Sales');
insert into department (name) values ('Legal');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Marketing');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Services');
insert into department (name) values ('Product Management');
insert into department (name) values ('Training');
insert into department (name) values ('Sales');
insert into department (name) values ('Engineering');
insert into department (name) values ('Product Management');
insert into department (name) values ('Support');
insert into department (name) values ('Services');
insert into department (name) values ('Business Development');
insert into department (name) values ('Product Management');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Product Management');
insert into department (name) values ('Accounting');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Business Development');
insert into department (name) values ('Engineering');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Training');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Services');
insert into department (name) values ('Business Development');
insert into department (name) values ('Business Development');
insert into department (name) values ('Training');
insert into department (name) values ('Legal');
insert into department (name) values ('Legal');
insert into department (name) values ('Services');
insert into department (name) values ('Product Management');
insert into department (name) values ('Product Management');
insert into department (name) values ('Accounting');
insert into department (name) values ('Engineering');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Sales');
insert into department (name) values ('Engineering');
insert into department (name) values ('Marketing');
insert into department (name) values ('Product Management');
insert into department (name) values ('Services');
insert into department (name) values ('Business Development');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Product Management');
insert into department (name) values ('Support');
insert into department (name) values ('Engineering');
insert into department (name) values ('Support');

-- Insert dummy data for comment table
insert into comment (comment) values ('urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi');
insert into comment (comment) values ('ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan');
insert into comment (comment) values ('rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio');
insert into comment (comment) values ('lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut');
insert into comment (comment) values ('proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in');
insert into comment (comment) values ('dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum');
insert into comment (comment) values ('justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna');
insert into comment (comment) values ('suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae');
insert into comment (comment) values ('pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat');
insert into comment (comment) values ('eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi');
insert into comment (comment) values ('posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into comment (comment) values ('nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla');
insert into comment (comment) values ('auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc');
insert into comment (comment) values ('integer pede justo lacinia eget tincidunt eget tempus vel pede');
insert into comment (comment) values ('libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc');
insert into comment (comment) values ('mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh');
insert into comment (comment) values ('ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros');
insert into comment (comment) values ('elementum ligula vehicula consequat morbi a ipsum integer a nibh');
insert into comment (comment) values ('mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient');
insert into comment (comment) values ('nibh fusce lacus purus aliquet at feugiat non pretium quis lectus');
insert into comment (comment) values ('in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum');
insert into comment (comment) values ('interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa');
insert into comment (comment) values ('ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus');
insert into comment (comment) values ('nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris');
insert into comment (comment) values ('vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper');
insert into comment (comment) values ('ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi');
insert into comment (comment) values ('quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus');
insert into comment (comment) values ('pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie');
insert into comment (comment) values ('quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis');
insert into comment (comment) values ('ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into comment (comment) values ('vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa');
insert into comment (comment) values ('ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl');
insert into comment (comment) values ('ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus');
insert into comment (comment) values ('adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy');
insert into comment (comment) values ('faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est');
insert into comment (comment) values ('nulla suscipit ligula in lacus curabitur at ipsum ac tellus');
insert into comment (comment) values ('urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi');
insert into comment (comment) values ('quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst');
insert into comment (comment) values ('eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula');
insert into comment (comment) values ('quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a');
insert into comment (comment) values ('in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque');
insert into comment (comment) values ('ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at');
insert into comment (comment) values ('pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in');
insert into comment (comment) values ('vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into comment (comment) values ('in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat');
insert into comment (comment) values ('duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum');
insert into comment (comment) values ('vulputate ut ultrices vel augue vestibulum ante ipsum primis in');
insert into comment (comment) values ('neque sapien placerat ante nulla justo aliquam quis turpis eget');
insert into comment (comment) values ('ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac');
insert into comment (comment) values ('congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu');
insert into comment (comment) values ('ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum');
insert into comment (comment) values ('orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum');
insert into comment (comment) values ('curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae');
insert into comment (comment) values ('justo eu massa donec dapibus duis at velit eu est congue elementum in hac');
insert into comment (comment) values ('in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non');
insert into comment (comment) values ('dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet');
insert into comment (comment) values ('vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis');
insert into comment (comment) values ('pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut');
insert into comment (comment) values ('ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce');
insert into comment (comment) values ('rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean');
insert into comment (comment) values ('ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur');
insert into comment (comment) values ('pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie');
insert into comment (comment) values ('mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper');
insert into comment (comment) values ('faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui');
insert into comment (comment) values ('eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis');
insert into comment (comment) values ('lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus');
insert into comment (comment) values ('nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et');
insert into comment (comment) values ('libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into comment (comment) values ('magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus');
insert into comment (comment) values ('amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor');
insert into comment (comment) values ('sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis');
insert into comment (comment) values ('sapien quis libero nullam sit amet turpis elementum ligula vehicula');
insert into comment (comment) values ('in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec');
insert into comment (comment) values ('turpis donec posuere metus vitae ipsum aliquam non mauris morbi non');
insert into comment (comment) values ('arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo');
insert into comment (comment) values ('ac nibh fusce lacus purus aliquet at feugiat non pretium quis');
insert into comment (comment) values ('et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti');
insert into comment (comment) values ('ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id');
insert into comment (comment) values ('lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl');
insert into comment (comment) values ('sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique');
insert into comment (comment) values ('tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse');
insert into comment (comment) values ('consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo');
insert into comment (comment) values ('maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat');
insert into comment (comment) values ('volutpat quam pede lobortis ligula sit amet eleifend pede libero');
insert into comment (comment) values ('pellentesque quisque porta volutpat erat quisque erat eros viverra eget');
insert into comment (comment) values ('dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer');
insert into comment (comment) values ('ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices');
insert into comment (comment) values ('ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate');
insert into comment (comment) values ('lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum');
insert into comment (comment) values ('accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam');
insert into comment (comment) values ('urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non');
insert into comment (comment) values ('non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla');
insert into comment (comment) values ('justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla');
insert into comment (comment) values ('sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec');
insert into comment (comment) values ('amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt');
insert into comment (comment) values ('augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus');
insert into comment (comment) values ('ligula sit amet eleifend pede libero quis orci nullam molestie nibh');
insert into comment (comment) values ('nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa');
insert into comment (comment) values ('dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum');
insert into comment (comment) values ('quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor');


-- Insert dummy data for faculty table
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (670, 'Melosa', 'Hysom', 'sem', 'mhysom0@nymag.com', '257-377-7601', 'Account Coordinator', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (635, 'Austina', 'Gallichiccio', 'elementum', 'agallichiccio1@networkadvertising.org', '587-745-0052', 'Account Representative III', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (551, 'Mile', 'Ambler', 'eget', 'mambler2@mayoclinic.com', '264-758-8413', 'Tax Accountant', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (336, 'Albert', 'McCumskay', 'natoque', 'amccumskay3@comcast.net', '627-108-7001', 'Senior Cost Accountant', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (789, 'Dallon', 'Follitt', 'ut', 'dfollitt4@taobao.com', '291-485-6397', 'Clinical Specialist', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (384, 'Kirk', 'Bawden', 'malesuada', 'kbawden5@va.gov', '304-121-8897', 'Structural Engineer', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (354, 'Camellia', 'Matiewe', 'praesent', 'cmatiewe6@prweb.com', '562-760-8794', 'Account Coordinator', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (417, 'Nanine', 'Stollen', 'velit', 'nstollen7@army.mil', '108-428-5245', 'Budget/Accounting Analyst II', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (29, 'Constantine', 'Tiplady', 'donec', 'ctiplady8@cyberchimps.com', '665-173-1277', 'Research Nurse', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (682, 'Blanche', 'Duxfield', 'id', 'bduxfield9@google.co.uk', '220-343-6062', 'Administrative Assistant II', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (531, 'Hartwell', 'Ivashintsov', 'sollicitudin', 'hivashintsova@hud.gov', '257-370-9929', 'Structural Engineer', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (193, 'Pamelina', 'Tschiersch', 'augue', 'ptschierschb@bing.com', '470-877-6153', 'Senior Financial Analyst', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (517, 'Chancey', 'Rabjohn', 'sodales', 'crabjohnc@ebay.co.uk', '186-767-6422', 'Operator', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (461, 'Herold', 'Hendriks', 'quis', 'hhendriksd@lulu.com', '239-446-8929', 'Web Developer II', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (639, 'Bamby', 'Graeser', 'quisque', 'bgraesere@tripadvisor.com', '634-430-6956', 'Statistician III', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (530, 'Marla', 'O''Regan', 'quisque', 'moreganf@e-recht24.de', '870-931-4634', 'Safety Technician I', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (857, 'Oren', 'Berth', 'est', 'oberthg@dagondesign.com', '524-922-6205', 'Safety Technician IV', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (273, 'Major', 'Fletham', 'odio', 'mflethamh@phoca.cz', '910-940-4110', 'Biostatistician IV', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (130, 'Bevon', 'Magwood', 'ornare', 'bmagwoodi@plala.or.jp', '125-507-6937', 'Help Desk Operator', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (331, 'Durand', 'Brikner', 'viverra', 'dbriknerj@github.io', '984-336-5121', 'Registered Nurse', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (377, 'Layla', 'Renvoise', 'orci', 'lrenvoisek@usatoday.com', '793-734-5326', 'Analyst Programmer', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (855, 'Eloise', 'Corfield', 'lectus', 'ecorfieldl@addtoany.com', '306-582-6276', 'Staff Accountant II', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (316, 'Miltie', 'Lincoln', 'aliquam', 'mlincolnm@un.org', '227-474-0077', 'Automation Specialist IV', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (435, 'Lexi', 'Penrose', 'phasellus', 'lpenrosen@wikia.com', '649-857-2666', 'Sales Representative', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (456, 'Abramo', 'Petriello', 'montes', 'apetrielloo@goo.ne.jp', '627-263-0889', 'Safety Technician IV', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (902, 'Agace', 'Asmus', 'elementum', 'aasmusp@salon.com', '154-128-1873', 'Geologist IV', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (788, 'Devland', 'Dyer', 'pellentesque', 'ddyerq@fda.gov', '822-720-4803', 'Health Coach III', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (972, 'Lydie', 'Clothier', 'justo', 'lclothierr@ftc.gov', '456-128-0296', 'Senior Editor', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (806, 'Allison', 'Emslie', 'enim', 'aemslies@webmd.com', '328-697-5346', 'Technical Writer', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (147, 'Luce', 'McGettrick', 'tincidunt', 'lmcgettrickt@dion.ne.jp', '248-222-1827', 'Information Systems Manager', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (955, 'Elmira', 'Megany', 'turpis', 'emeganyu@creativecommons.org', '885-712-1455', 'Senior Cost Accountant', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (731, 'Reinaldos', 'Piercy', 'vel', 'rpiercyv@hubpages.com', '280-298-4766', 'Librarian', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (394, 'Kylila', 'Catlin', 'felis', 'kcatlinw@theatlantic.com', '299-399-3737', 'Health Coach II', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (557, 'Trumann', 'Lawden', 'non', 'tlawdenx@hubpages.com', '468-170-9759', 'Chief Design Engineer', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (860, 'Kacie', 'Runchman', 'nulla', 'krunchmany@issuu.com', '240-457-0239', 'Structural Engineer', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (970, 'Felice', 'Causbey', 'ac', 'fcausbeyz@berkeley.edu', '886-741-4912', 'Web Designer IV', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (648, 'Brook', 'Critchlow', 'etiam', 'bcritchlow10@people.com.cn', '591-262-1746', 'VP Product Management', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (898, 'Aldin', 'Chessman', 'sit', 'achessman11@aboutads.info', '770-217-1836', 'Associate Professor', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (252, 'Terrence', 'Bending', 'nulla', 'tbending12@purevolume.com', '276-453-4071', 'Environmental Specialist', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (295, 'Jayme', 'Werrit', 'curae', 'jwerrit13@ucla.edu', '570-387-2261', 'Staff Scientist', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (488, 'Natka', 'Christofe', 'pede', 'nchristofe14@parallels.com', '499-995-6041', 'Senior Cost Accountant', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (946, 'Kinsley', 'Yakob', 'eu', 'kyakob15@squidoo.com', '831-270-6555', 'Chemical Engineer', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (657, 'Dru', 'Mc Queen', 'nunc', 'dmcqueen16@umich.edu', '385-393-9168', 'Occupational Therapist', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (522, 'Justino', 'Rhoades', 'dapibus', 'jrhoades17@loc.gov', '439-821-5975', 'Administrative Officer', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (745, 'Courtney', 'Lehrian', 'habitasse', 'clehrian18@yahoo.com', '404-347-0060', 'Financial Analyst', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (623, 'Carola', 'Shovelbottom', 'urna', 'cshovelbottom19@163.com', '649-273-5137', 'Electrical Engineer', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (242, 'Anatola', 'Barsam', 'non', 'abarsam1a@1688.com', '601-116-3166', 'Assistant Media Planner', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (297, 'Gilly', 'Pimme', 'at', 'gpimme1b@mac.com', '568-760-0596', 'Speech Pathologist', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (632, 'Gaby', 'Stretton', 'felis', 'gstretton1c@e-recht24.de', '959-693-9234', 'Quality Engineer', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (847, 'Kym', 'Amiss', 'turpis', 'kamiss1d@ycombinator.com', '992-572-3694', 'Developer I', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (268, 'Ted', 'Sinclair', 'phasellus', 'tsinclair1e@artisteer.com', '811-134-9185', 'Programmer III', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (753, 'Dacia', 'Hugo', 'etiam', 'dhugo1f@yolasite.com', '351-619-0196', 'Computer Systems Analyst IV', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (957, 'Biron', 'Pittendreigh', 'consequat', 'bpittendreigh1g@google.de', '717-734-2966', 'Media Manager I', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (990, 'Cornell', 'Rainger', 'amet', 'crainger1h@furl.net', '347-748-4341', 'Engineer IV', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (750, 'Rouvin', 'Haygreen', 'in', 'rhaygreen1i@bing.com', '659-805-6848', 'Civil Engineer', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (951, 'Petra', 'McCaskill', 'sit', 'pmccaskill1j@opensource.org', '276-955-7976', 'Technical Writer', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (871, 'Ursulina', 'Nano', 'non', 'unano1k@bloomberg.com', '128-757-4056', 'Associate Professor', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (287, 'Humfrid', 'Eminson', 'mauris', 'heminson1l@list-manage.com', '598-523-3287', 'Quality Engineer', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (590, 'Steward', 'Whoston', 'sapien', 'swhoston1m@cnbc.com', '211-951-7068', 'Social Worker', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (181, 'Winonah', 'Syres', 'dui', 'wsyres1n@dropbox.com', '168-929-6428', 'Dental Hygienist', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (766, 'Clair', 'Gratrix', 'tincidunt', 'cgratrix1o@odnoklassniki.ru', '571-699-7120', 'Software Test Engineer III', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (236, 'Nonie', 'Berceros', 'in', 'nberceros1p@google.it', '589-787-3995', 'Human Resources Manager', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (586, 'Nerissa', 'Seabridge', 'vel', 'nseabridge1q@macromedia.com', '346-880-5470', 'Civil Engineer', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (421, 'Janenna', 'Jozaitis', 'orci', 'jjozaitis1r@harvard.edu', '376-341-7273', 'Senior Sales Associate', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (158, 'Man', 'Extence', 'vel', 'mextence1s@elegantthemes.com', '531-100-0221', 'Data Coordinator', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (982, 'Germaine', 'Clarke', 'sit', 'gclarke1t@exblog.jp', '394-290-6665', 'Teacher', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (460, 'Mauricio', 'Ridsdell', 'hac', 'mridsdell1u@people.com.cn', '541-893-6753', 'Physical Therapy Assistant', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (67, 'Reynard', 'Rene', 'dolor', 'rrene1v@theglobeandmail.com', '111-915-8416', 'Business Systems Development Analyst', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (11, 'Phil', 'Huetson', 'quam', 'phuetson1w@narod.ru', '871-389-3587', 'Legal Assistant', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (0, 'Gabbey', 'Tomkins', 'vel', 'gtomkins1x@newyorker.com', '772-908-2059', 'Senior Financial Analyst', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (964, 'Oralla', 'Von Der Empten', 'quam', 'ovonderempten1y@bloglines.com', '998-525-9251', 'Director of Sales', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (689, 'Fernanda', 'Jansie', 'non', 'fjansie1z@spiegel.de', '222-841-0908', 'Database Administrator I', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (489, 'Axel', 'Carrabott', 'lobortis', 'acarrabott20@nps.gov', '806-283-8639', 'Analog Circuit Design manager', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (164, 'Lynnet', 'Adrienne', 'in', 'ladrienne21@uiuc.edu', '864-393-8432', 'Pharmacist', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (81, 'Zola', 'Francescone', 'lobortis', 'zfrancescone22@oracle.com', '869-712-2572', 'Data Coordinator', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (679, 'Guthrey', 'Durbann', 'amet', 'gdurbann23@comcast.net', '236-985-6872', 'Help Desk Operator', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (455, 'Allis', 'Horburgh', 'viverra', 'ahorburgh24@statcounter.com', '435-871-1835', 'Nurse Practicioner', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (289, 'Rory', 'Illes', 'aliquam', 'rilles25@icq.com', '982-365-3833', 'Help Desk Operator', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (565, 'Cecil', 'Focke', 'orci', 'cfocke26@wired.com', '200-812-2423', 'GIS Technical Architect', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (746, 'Nelia', 'Wickham', 'cursus', 'nwickham27@t.co', '468-438-9942', 'Programmer II', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (207, 'Anny', 'Goward', 'ligula', 'agoward28@ning.com', '252-677-9115', 'Tax Accountant', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (498, 'Wallache', 'Crunden', 'amet', 'wcrunden29@who.int', '729-454-6498', 'Food Chemist', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (523, 'Isadore', 'Blaxlande', 'suspendisse', 'iblaxlande2a@about.com', '814-242-7427', 'Marketing Manager', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (283, 'Iago', 'Peters', 'id', 'ipeters2b@dedecms.com', '247-320-0089', 'Compensation Analyst', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (872, 'Humbert', 'Tezure', 'purus', 'htezure2c@paypal.com', '712-927-3374', 'Administrative Officer', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (223, 'Ora', 'Penning', 'viverra', 'openning2d@elegantthemes.com', '716-408-7985', 'Accounting Assistant IV', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (638, 'Bradford', 'Lamas', 'sollicitudin', 'blamas2e@tumblr.com', '746-989-3795', 'Marketing Manager', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (859, 'Kirstin', 'Goeff', 'in', 'kgoeff2f@e-recht24.de', '407-304-4505', 'Quality Control Specialist', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (379, 'Tuck', 'Talkington', 'eu', 'ttalkington2g@cmu.edu', '127-491-7750', 'Paralegal', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (767, 'Bogey', 'Ordemann', 'aenean', 'bordemann2h@amazon.de', '867-562-7474', 'Research Nurse', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (599, 'Annabelle', 'Hargie', 'tortor', 'ahargie2i@wp.com', '908-670-2587', 'Account Coordinator', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (663, 'Brit', 'Garlic', 'dictumst', 'bgarlic2j@delicious.com', '134-183-6143', 'Technical Writer', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (229, 'Anitra', 'Van''t Hoff', 'in', 'avanthoff2k@free.fr', '210-307-9274', 'Account Coordinator', true, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (234, 'Claude', 'Housiaux', 'duis', 'chousiaux2l@taobao.com', '729-272-2126', 'Systems Administrator I', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (148, 'Tallia', 'Curryer', 'sem', 'tcurryer2m@angelfire.com', '307-693-1443', 'Nuclear Power Engineer', true, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (469, 'Erick', 'Reubens', 'in', 'ereubens2n@blog.com', '960-463-4828', 'Librarian', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (933, 'Stavros', 'Fiddyment', 'luctus', 'sfiddyment2o@scientificamerican.com', '148-532-5029', 'Sales Representative', false, true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (727, 'Cary', 'Coode', 'sit', 'ccoode2p@cdbaby.com', '794-463-7838', 'Environmental Tech', true, true);
# insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (130, 'Cami', 'Bellwood', 'eros', 'cbellwood2q@unicef.org', '463-973-5158', 'Programmer IV', false, false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, is_deleted) values (520, 'Hildegarde', 'Lucken', 'bibendum', 'hlucken2r@state.tx.us', '218-520-0314', 'Marketing Assistant', true, false);

