-- Insert dummy data for department table
insert into department (name) values ('Human Resources');
insert into department (name) values ('Marketing');
insert into department (name) values ('Accounting');
insert into department (name) values ('Engineering');
insert into department (name) values ('Business Development');
insert into department (name) values ('Business Development');
insert into department (name) values ('Services');
insert into department (name) values ('Business Development');
insert into department (name) values ('Services');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Training');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Services');
insert into department (name) values ('Business Development');
insert into department (name) values ('Training');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Sales');
insert into department (name) values ('Business Development');
insert into department (name) values ('Marketing');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Support');
insert into department (name) values ('Product Management');
insert into department (name) values ('Engineering');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Services');
insert into department (name) values ('Engineering');
insert into department (name) values ('Support');
insert into department (name) values ('Business Development');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Services');
insert into department (name) values ('Training');
insert into department (name) values ('Product Management');
insert into department (name) values ('Business Development');
insert into department (name) values ('Engineering');
insert into department (name) values ('Engineering');
insert into department (name) values ('Training');
insert into department (name) values ('Business Development');
insert into department (name) values ('Accounting');
insert into department (name) values ('Services');
insert into department (name) values ('Support');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Support');
insert into department (name) values ('Training');
insert into department (name) values ('Marketing');
insert into department (name) values ('Legal');
insert into department (name) values ('Services');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Support');
insert into department (name) values ('Product Management');
insert into department (name) values ('Engineering');
insert into department (name) values ('Sales');
insert into department (name) values ('Legal');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Marketing');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Services');
insert into department (name) values ('Product Management');
insert into department (name) values ('Training');
insert into department (name) values ('Sales');
insert into department (name) values ('Engineering');
insert into department (name) values ('Product Management');
insert into department (name) values ('Support');
insert into department (name) values ('Services');
insert into department (name) values ('Business Development');
insert into department (name) values ('Product Management');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Product Management');
insert into department (name) values ('Accounting');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Business Development');
insert into department (name) values ('Engineering');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Training');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Services');
insert into department (name) values ('Business Development');
insert into department (name) values ('Business Development');
insert into department (name) values ('Training');
insert into department (name) values ('Legal');
insert into department (name) values ('Legal');
insert into department (name) values ('Services');
insert into department (name) values ('Product Management');
insert into department (name) values ('Product Management');
insert into department (name) values ('Accounting');
insert into department (name) values ('Engineering');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Sales');
insert into department (name) values ('Engineering');
insert into department (name) values ('Marketing');
insert into department (name) values ('Product Management');
insert into department (name) values ('Services');
insert into department (name) values ('Business Development');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Product Management');
insert into department (name) values ('Support');
insert into department (name) values ('Engineering');
insert into department (name) values ('Support');

-- Insert dummy data for comment table
insert into comment (comment) values ('urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi');
insert into comment (comment) values ('ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan');
insert into comment (comment) values ('rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio');
insert into comment (comment) values ('lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut');
insert into comment (comment) values ('proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in');
insert into comment (comment) values ('dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum');
insert into comment (comment) values ('justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna');
insert into comment (comment) values ('suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae');
insert into comment (comment) values ('pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat');
insert into comment (comment) values ('eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi');
insert into comment (comment) values ('posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into comment (comment) values ('nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla');
insert into comment (comment) values ('auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc');
insert into comment (comment) values ('integer pede justo lacinia eget tincidunt eget tempus vel pede');
insert into comment (comment) values ('libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc');
insert into comment (comment) values ('mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh');
insert into comment (comment) values ('ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros');
insert into comment (comment) values ('elementum ligula vehicula consequat morbi a ipsum integer a nibh');
insert into comment (comment) values ('mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient');
insert into comment (comment) values ('nibh fusce lacus purus aliquet at feugiat non pretium quis lectus');
insert into comment (comment) values ('in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum');
insert into comment (comment) values ('interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa');
insert into comment (comment) values ('ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus');
insert into comment (comment) values ('nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris');
insert into comment (comment) values ('vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper');
insert into comment (comment) values ('ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi');
insert into comment (comment) values ('quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus');
insert into comment (comment) values ('pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie');
insert into comment (comment) values ('quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis');
insert into comment (comment) values ('ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into comment (comment) values ('vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa');
insert into comment (comment) values ('ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl');
insert into comment (comment) values ('ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus');
insert into comment (comment) values ('adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy');
insert into comment (comment) values ('faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est');
insert into comment (comment) values ('nulla suscipit ligula in lacus curabitur at ipsum ac tellus');
insert into comment (comment) values ('urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi');
insert into comment (comment) values ('quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst');
insert into comment (comment) values ('eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula');
insert into comment (comment) values ('quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a');
insert into comment (comment) values ('in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque');
insert into comment (comment) values ('ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at');
insert into comment (comment) values ('pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in');
insert into comment (comment) values ('vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into comment (comment) values ('in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat');
insert into comment (comment) values ('duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum');
insert into comment (comment) values ('vulputate ut ultrices vel augue vestibulum ante ipsum primis in');
insert into comment (comment) values ('neque sapien placerat ante nulla justo aliquam quis turpis eget');
insert into comment (comment) values ('ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac');
insert into comment (comment) values ('congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu');
insert into comment (comment) values ('ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum');
insert into comment (comment) values ('orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum');
insert into comment (comment) values ('curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae');
insert into comment (comment) values ('justo eu massa donec dapibus duis at velit eu est congue elementum in hac');
insert into comment (comment) values ('in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non');
insert into comment (comment) values ('dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet');
insert into comment (comment) values ('vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis');
insert into comment (comment) values ('pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut');
insert into comment (comment) values ('ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce');
insert into comment (comment) values ('rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean');
insert into comment (comment) values ('ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur');
insert into comment (comment) values ('pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie');
insert into comment (comment) values ('mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper');
insert into comment (comment) values ('faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui');
insert into comment (comment) values ('eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis');
insert into comment (comment) values ('lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus');
insert into comment (comment) values ('nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et');
insert into comment (comment) values ('libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into comment (comment) values ('magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus');
insert into comment (comment) values ('amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor');
insert into comment (comment) values ('sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis');
insert into comment (comment) values ('sapien quis libero nullam sit amet turpis elementum ligula vehicula');
insert into comment (comment) values ('in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec');
insert into comment (comment) values ('turpis donec posuere metus vitae ipsum aliquam non mauris morbi non');
insert into comment (comment) values ('arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo');
insert into comment (comment) values ('ac nibh fusce lacus purus aliquet at feugiat non pretium quis');
insert into comment (comment) values ('et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti');
insert into comment (comment) values ('ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id');
insert into comment (comment) values ('lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl');
insert into comment (comment) values ('sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique');
insert into comment (comment) values ('tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse');
insert into comment (comment) values ('consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo');
insert into comment (comment) values ('maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat');
insert into comment (comment) values ('volutpat quam pede lobortis ligula sit amet eleifend pede libero');
insert into comment (comment) values ('pellentesque quisque porta volutpat erat quisque erat eros viverra eget');
insert into comment (comment) values ('dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer');
insert into comment (comment) values ('ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices');
insert into comment (comment) values ('ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate');
insert into comment (comment) values ('lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum');
insert into comment (comment) values ('accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam');
insert into comment (comment) values ('urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non');
insert into comment (comment) values ('non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla');
insert into comment (comment) values ('justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla');
insert into comment (comment) values ('sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec');
insert into comment (comment) values ('amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt');
insert into comment (comment) values ('augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus');
insert into comment (comment) values ('ligula sit amet eleifend pede libero quis orci nullam molestie nibh');
insert into comment (comment) values ('nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa');
insert into comment (comment) values ('dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum');
insert into comment (comment) values ('quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor');


-- Insert dummy data for faculty table
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, role, is_deleted) values (1, 'Nyssa', 'Steanyng', 'dG2!jmRk~ay''x', 'nsteanyng0@craigslist.org', '329-542-2413', 'Staff Accountant III', false, 'ADMIN', true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, role, is_deleted) values (2, 'Nicoline', 'Guillond', 'hG0*=QphB$H', 'nguillond1@auda.org.au', '101-811-1791', 'Actuary', false, 'USER', false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, role, is_deleted) values (3, 'Ben', 'Board', 'rR9!J|GyO?mWpe<u', 'bboard2@amazonaws.com', '616-215-6143', 'Assistant Manager', true, 'ADMIN', true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, role, is_deleted) values (4, 'Maia', 'Laughnan', 'cU7''fz2t', 'mlaughnan3@theglobeandmail.com', '762-567-2601', 'Payment Adjustment Coordinator', true, 'ADMIN', false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, role, is_deleted) values (5, 'Lamar', 'Spinola', 'eT1`S@&,', 'lspinola4@uol.com.br', '822-395-7855', 'Pharmacist', true, 'ADMIN', false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, role, is_deleted) values (6, 'Chrisse', 'Bernath', 'iC3{m"gyk', 'cbernath5@newyorker.com', '753-753-6594', 'Registered Nurse', false, 'USER', false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, role, is_deleted) values (7, 'Roldan', 'Cuthill', 'iD9''VCZm{W', 'rcuthill6@digg.com', '299-278-8484', 'Design Engineer', false, 'ADMIN', false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, role, is_deleted) values (8, 'Kristel', 'Van Eeden', 'pC8#=!?m|J!', 'kvaneeden7@bandcamp.com', '844-361-3716', 'Software Engineer II', false, 'USER', true);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, role, is_deleted) values (9, 'Ursola', 'Grimme', 'qW2_}iYC1GDXgRL', 'ugrimme8@uiuc.edu', '351-334-3674', 'VP Accounting', true, 'USER', false);
insert into faculty (id, first_name, last_name, password, email, phone_number, title, is_admin, role, is_deleted) values (10, 'Cathleen', 'Clotworthy', 'eT3~vd7tLL', 'cclotworthy9@bloglovin.com', '263-662-3320', 'Pharmacist', true, 'ADMIN', false);
